Usage: papermill [OPTIONS] NOTEBOOK_PATH [OUTPUT_PATH]
Try "papermill -h" for help.

Error: Got unexpected extra argument ( )
Usage: papermill [OPTIONS] NOTEBOOK_PATH [OUTPUT_PATH]
Try "papermill -h" for help.

Error: Got unexpected extra argument ( )
Usage: papermill [OPTIONS] NOTEBOOK_PATH [OUTPUT_PATH]
Try "papermill -h" for help.

Error: Got unexpected extra argument ( )
Usage: papermill [OPTIONS] NOTEBOOK_PATH [OUTPUT_PATH]
Try "papermill -h" for help.

Error: Got unexpected extra argument ( )
Usage: papermill [OPTIONS] NOTEBOOK_PATH [OUTPUT_PATH]
Try "papermill -h" for help.

Error: Got unexpected extra argument ( )
Usage: papermill [OPTIONS] NOTEBOOK_PATH [OUTPUT_PATH]
Try "papermill -h" for help.

Error: Got unexpected extra argument ( )
Usage: papermill [OPTIONS] NOTEBOOK_PATH [OUTPUT_PATH]
Try "papermill -h" for help.

Error: Got unexpected extra argument ( )
Usage: papermill [OPTIONS] NOTEBOOK_PATH [OUTPUT_PATH]
Try "papermill -h" for help.

Error: Got unexpected extra argument ( )
Usage: papermill [OPTIONS] NOTEBOOK_PATH [OUTPUT_PATH]
Try "papermill -h" for help.

Error: Got unexpected extra argument ( )
Usage: papermill [OPTIONS] NOTEBOOK_PATH [OUTPUT_PATH]
Try "papermill -h" for help.

Error: Got unexpected extra argument ( )
Usage: papermill [OPTIONS] NOTEBOOK_PATH [OUTPUT_PATH]
Try "papermill -h" for help.

Error: Got unexpected extra argument ( )
Usage: papermill [OPTIONS] NOTEBOOK_PATH [OUTPUT_PATH]
Try "papermill -h" for help.

Error: Got unexpected extra argument ( )
Usage: papermill [OPTIONS] NOTEBOOK_PATH [OUTPUT_PATH]
Try "papermill -h" for help.

Error: Got unexpected extra argument ( )
Usage: papermill [OPTIONS] NOTEBOOK_PATH [OUTPUT_PATH]
Try "papermill -h" for help.

Error: Got unexpected extra argument ( )
Usage: papermill [OPTIONS] NOTEBOOK_PATH [OUTPUT_PATH]
Try "papermill -h" for help.

Error: Got unexpected extra argument ( )
Traceback (most recent call last):
  File "/home/tristan/.local/bin/papermill", line 5, in <module>
    from papermill.cli import papermill
  File "/home/tristan/.local/lib/python3.8/site-packages/papermill/__init__.py", line 4, in <module>
    from .execute import execute_notebook
  File "/home/tristan/.local/lib/python3.8/site-packages/papermill/execute.py", line 9, in <module>
    from .iorw import get_pretty_path, local_file_io_cwd, load_notebook_node, write_ipynb
  File "/home/tristan/.local/lib/python3.8/site-packages/papermill/iorw.py", line 10, in <module>
    import requests
  File "/usr/lib/python3/dist-packages/requests/__init__.py", line 95, in <module>
    from urllib3.contrib import pyopenssl
  File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 12, in <module>
    from cryptography import x509
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 914, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1342, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1314, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1439, in find_spec
  File "<frozen importlib._bootstrap_external>", line 87, in _path_stat
KeyboardInterrupt
Usage: papermill [OPTIONS] NOTEBOOK_PATH [OUTPUT_PATH]
Try "papermill -h" for help.

Error: Got unexpected extra argument ( )
Usage: papermill [OPTIONS] NOTEBOOK_PATH [OUTPUT_PATH]
Try "papermill -h" for help.

Error: Got unexpected extra argument ( )
Usage: papermill [OPTIONS] NOTEBOOK_PATH [OUTPUT_PATH]
Try "papermill -h" for help.

Error: Got unexpected extra argument ( )
Usage: papermill [OPTIONS] NOTEBOOK_PATH [OUTPUT_PATH]
Try "papermill -h" for help.

Error: Got unexpected extra argument ( )
Usage: papermill [OPTIONS] NOTEBOOK_PATH [OUTPUT_PATH]
Try "papermill -h" for help.

Error: Got unexpected extra argument ( )
Usage: papermill [OPTIONS] NOTEBOOK_PATH [OUTPUT_PATH]
Try "papermill -h" for help.

Error: Got unexpected extra argument ( )
Usage: papermill [OPTIONS] NOTEBOOK_PATH [OUTPUT_PATH]
Try "papermill -h" for help.

Error: Got unexpected extra argument ( )
Traceback (most recent call last):
  File "/home/tristan/.local/bin/papermill", line 5, in <module>
    from papermill.cli import papermill
  File "/home/tristan/.local/lib/python3.8/site-packages/papermill/__init__.py", line 4, in <module>
    from .execute import execute_notebook
  File "/home/tristan/.local/lib/python3.8/site-packages/papermill/execute.py", line 9, in <module>
    from .iorw import get_pretty_path, local_file_io_cwd, load_notebook_node, write_ipynb
  File "/home/tristan/.local/lib/python3.8/site-packages/papermill/iorw.py", line 10, in <module>
    import requests
  File "/usr/lib/python3/dist-packages/requests/__init__.py", line 95, in <module>
    from urllib3.contrib import pyopenssl
  File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 16, in <module>
    from OpenSSL._util import (
  File "/usr/lib/python3/dist-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/usr/lib/python3/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 15, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
KeyboardInterrupt
Input Notebook:  euler_driver.ipynb
Output Notebook: euler_m04p2c0t1_strong.ipynb
Generating grammar tables from /home/tristan/.local/lib/python3.8/site-packages/blib2to3/Grammar.txt
Writing grammar tables to /home/tristan/.cache/black/20.8b1/Grammar3.8.5.final.0.pickle
Writing failed: [Errno 2] No such file or directory: '/home/tristan/.cache/black/20.8b1/tmp0qojn6el'
Generating grammar tables from /home/tristan/.local/lib/python3.8/site-packages/blib2to3/PatternGrammar.txt
Writing grammar tables to /home/tristan/.cache/black/20.8b1/PatternGrammar3.8.5.final.0.pickle
Writing failed: [Errno 2] No such file or directory: '/home/tristan/.cache/black/20.8b1/tmpgtzs0uqf'
Executing:   0%|          | 0/4 [00:00<?, ?cell/s]Executing notebook with kernel: python3
Executing:  25%|██▌       | 1/4 [00:01<00:03,  1.02s/cell]Kernel died while waiting for execute reply.
Executing:  75%|███████▌  | 3/4 [00:24<00:08,  8.80s/cell]Executing:  75%|███████▌  | 3/4 [00:24<00:08,  8.02s/cell]
Traceback (most recent call last):
  File "/home/tristan/.local/lib/python3.8/site-packages/nbclient/client.py", line 816, in async_execute_cell
    exec_reply = await self.task_poll_for_reply
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tristan/.local/lib/python3.8/site-packages/papermill/cli.py", line 240, in papermill
    execute_notebook(
  File "/home/tristan/.local/lib/python3.8/site-packages/papermill/execute.py", line 103, in execute_notebook
    nb = papermill_engines.execute_notebook_with_engine(
  File "/home/tristan/.local/lib/python3.8/site-packages/papermill/engines.py", line 49, in execute_notebook_with_engine
    return self.get_engine(engine_name).execute_notebook(nb, kernel_name, **kwargs)
  File "/home/tristan/.local/lib/python3.8/site-packages/papermill/engines.py", line 343, in execute_notebook
    cls.execute_managed_notebook(nb_man, kernel_name, log_output=log_output, **kwargs)
  File "/home/tristan/.local/lib/python3.8/site-packages/papermill/engines.py", line 402, in execute_managed_notebook
    return PapermillNotebookClient(nb_man, **final_kwargs).execute()
  File "/home/tristan/.local/lib/python3.8/site-packages/papermill/clientwrap.py", line 45, in execute
    self.papermill_execute_cells()
  File "/home/tristan/.local/lib/python3.8/site-packages/papermill/clientwrap.py", line 72, in papermill_execute_cells
    self.execute_cell(cell, index)
  File "/home/tristan/.local/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/tristan/.local/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/tristan/.local/lib/python3.8/site-packages/nbclient/client.py", line 820, in async_execute_cell
    raise DeadKernelError("Kernel died")
nbclient.exceptions.DeadKernelError: Kernel died
